# Generated by Django 3.2.5 on 2021-07-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
